### ISSUE TITLE
🚨 [Fix] 인기 게시글 조회 api - 403 에러

### ISSUE THREAD

**Issue by frombunny** [HSU-Likelion12-yourSide/YourSide-Server#129]
## 💡 About
네편 프론트 측에서 인기 게시글 조회 api로 요청을 보낼 경우, 403 에러가 발생한다고 하여
로컬에서 코드를 실행하고 콘솔 메시지를 확인해보니, 아래와 같은 오류가 발생했습니다!
> 024-10-21T16:47:38.409+09:00 ERROR 55510 --- [yourside] [nio-8080-exec-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : Table 'yourside_db.POSTING' doesn't exist

<br>

코드를 살펴보니, PostingRepository의 아래 부분으로 인하여 문제가 생긴다는 것을 알 수 있었습니다.
<img width="975" alt="image" src="https://github.com/user-attachments/assets/39cacc82-29b0-49fb-bb36-d9be4623f60c">

아마, `MySQL에서 테이블 이름이 소문자라면 쿼리에서도 테이블 이름을 소문자로 일치`시켜야 하기 때문에 이러한 오류가 발생한 것 같습니다!
따라서 저는 아래와 같이 수정하였고, 로컬에서 실행해보니 코드도 정상적으로 작동하였습니다 😄😄 
<img width="969" alt="image" src="https://github.com/user-attachments/assets/007706cb-9968-438d-bf80-10718698f9ed">

그런데 제가 이 리포지토리에 푸쉬할 수 있는 권한이 없어서.. 푸쉬를 하지는 못했습니다! 😢😢
아 ! 서버 내에서는 임의로 제가 직접 코드를 수정을 하여 현재 서버로 요청을 보낼 때는 아무런 문제가 없습니다 🐰✌️✌️
알려드려야 할 것 같아서 이슈를 작성하였습니다 ~! @gesal03 @khyaejin 
좋은 하루 되세용 ~ 🍀 

## 📝 To Do

- [x] 새로운 기능 A 추가
- [x] 새로운 기능 B 추가
- [x] 테스트 코드 작성

## ✅ Issue check list

- [ ] Assignees, Labels 확인하기

**Comment by gesal03** [comment]
그렇군요

**Comment by khyaejin** [comment]
로컬에서는 돌아갔었는데 신기하네요..!! 원인 찾고 수정해주셔서 너무 감사합니다! 
#132 새로 이슈 만들어서 깃에 올라가있는 코드도 수정해두었습니다!

**Comment by gesal03** [comment]
오호 흥미로운 오류군요!!
고생하셨습니다~
@frombunny

**Comment by frombunny** [comment]
> 오호 흥미로운 오류군요!! 고생하셨습니다~ @frombunny

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㄱㅋㄱㅋㅋㅋㅋㅋㅋㅋ
